### ISSUE TITLE
In modalità development, npm install deve risolvere i pacchetti localmente e non nell'organizzazione

### ISSUE THREAD

**Issue by andreastedile** [carlocorradini/graphmarket#166]
Quando costruiamo un'immagine Docker, lanciamo il comando `npm install` che risolve le dipendenze e le installa.
Alcune di queste dipendenze si trovano online, sulla nostra organizzazione npm.
Quando sviluppiamo in modalità development, ovviamente noi non vogliamo che `npm install` risolvi le dipendenze online e le scarichi dalla nostra organizzazione, ma usi completamente i package in locale.
Ad esempio:
- Modifico il package _helpers_,
- Aggiorno la versione di _helpers_ nel `package.json`, sia del package _helpers_ che dei package dei servizi,
- Lancio `npm install` su ogni servizio. Questi servizi otterranno i cambiamenti di _helpers_.
L'intera procedura deve prevedere l'assenza di qualsiasi commit, in quanto si tratta appunto di testare modifiche prima di pubblicarle e renderle visibili all'organizzazione.
Come facciamo a realizzare ciò? Dobbiamo far sì che questo meccanismo funzioni sia in ambiente di sviluppo senza Docker, che con Docker.

**Comment by andreastedile** [comment]
Mi _sembra_ che una cosa del genere si possa fare con [localpaths](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#local-paths).
Ho provato ad applicare questa soluzione in Docker:
![image](https://user-images.githubusercontent.com/39307731/106132117-d2218200-6163-11eb-94d6-3fcb793d79c7.png)
Il razionale dietro questo tentativo è che, se forzo npm a risolvere un pacchetto localmente  (`npm install --save ../graphmarket-helpers`) ed installarlo, successivamente, al comando `npm install`, npm vedrà che helpers è già installato e non proverà a risoverlo online, con l'organizzazione.

L'immagine viene costruita senza problemi.
Tuttavia, appena la eseguo in un container, ho il seguente errore:
```
Error: Cannot find module '/graphmarket/packages/graphmarket-service-products/node_modules/@graphmarket/helpers/build/index.js'. Please verify that the package.json has a valid "main" entry
     at tryPackage (internal/modules/cjs/loader.js:303:19)
     at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
     at Function.Module._resolveFilename (/graphmarket/packages/graphmarket-service-products/node_modules/tsconfig-paths/lib/register.js:75:40)
     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
     at Module.require (internal/modules/cjs/loader.js:952:19)
     at require (internal/modules/cjs/helpers.js:88:18)
     at Object.<anonymous> (/graphmarket/packages/graphmarket-service-products/src/config/env.ts:3:1)
     at Module._compile (internal/modules/cjs/loader.js:1063:30)
     at Module._compile (/graphmarket/packages/graphmarket-service-products/node_modules/source-map-support/source-map-support.js:547:25)
 [ERROR] 11:07:26 Error: Cannot find module '/graphmarket/packages/graphmarket-service-products/node_modules/@graphmarket/helpers/build/index.js'. Please verify that the package.json has a valid "main" entry
```
Mi servirebbe aiuto poiché non me ne intendo molto di npm né javascript.

**Comment by andreastedile** [comment]
Per via del design e della struttura dell'applicazione, questa cosa non è possibile. Docker verrà solo usato come tool per deployment in ambiente produzione, ma non development o testing
